[package]
name = "nbnf_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
nbnf_language = { path = "../nbnf_language" }
quote = "1"
syn = { version = "2", features = ["full"] }
