[package]
name = "nbnf_language"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
nom = { workspace =  true }
nom-language = "0"
prettyplease = "0"
proc-macro2 = "1"
quote = { workspace =  true }
syn = { workspace =  true }
