[package]
name = "nbnf_language"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
nom = "8"
nom-language = "0"
prettyplease = "0"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
